version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vkharkivsk
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ../weatherapi
    working_dir: /usr/src/app
    depends_on:
      - db
    environment:
      PORT: 3001
      HOST: localhost
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: vkharkivsk
      DB_PASSWORD: password
      DB_NAME: weatherdb
    volumes:
      - ../weatherapi:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    command: sh -c "npx sequelize-cli db:migrate && npm start"

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - app

volumes:
  pgdata:
